---
- hosts: all
  gather_facts: true

  vars:
    nodejs_version: "6"
    debian_repo_version: "6.x"
    site_name: 192.168.50.4
    site_dir: /home/vagrant/ynos/dist
    letsencrypt_email: sergey.ukustov@machinomy.com
    yarn_version: '0.27.5'
    machinomy_path: '~/machinomy'
    ynos_path: '~/ynos'

  environment:
    NODE_ENV: vagrant

  tasks:
    - apt:
        name: g++
      become: true

    - name: Install  software-properties-common
      apt:
        name: software-properties-common
        update_cache: yes
      become: true

    - name: Set up ethereum PPA
      apt_repository:
        repo: "ppa:ethereum/ethereum"
        update_cache: yes
      become: true

    - name: Install geth
      apt:
        name: ethereum
      become: true

    - name: Ensure the system can use the HTTPS transport for APT
      stat:
        path: /usr/lib/apt/methods/https
      register: apt_https_transport

    - name: Install HTTPS transport for APT
      apt:
        pkg: apt-transport-https
        state: installed
      when: not apt_https_transport.stat.exists

    - name: Import the NodeSource GPG key into apt
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present
      become: yes

    - name: Add NodeSource deb repository
      apt_repository:
        repo: 'deb https://deb.nodesource.com/node_{{ debian_repo_version }} {{ ansible_distribution_release }} main'
        state: present
      become: yes

    - name: Add NodeSource deb-src repository
      apt_repository:
        repo: 'deb-src https://deb.nodesource.com/node_{{ debian_repo_version }} {{ ansible_distribution_release }} main'
        state: present
      become: yes

    - name: Install Node.js
      apt:
        pkg:
          - nodejs={{ nodejs_version }}*
        state: installed
        update_cache: yes
      become: yes

    - name: Install nginx
      apt:
        pkg: nginx
        state: installed
      become: yes

    - name: Deactivate the default nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      become: yes

    - name: Copy the site config
      template:
        src: templates/site.conf.j2
        dest: "/etc/nginx/sites-available/{{site_name}}.conf"
      become: yes

    - name: Activate the site
      file:
        src: "/etc/nginx/sites-available/{{site_name}}.conf"
        dest: "/etc/nginx/sites-enabled/{{site_name}}.conf"
        state: link
      become: yes

    - name: Configure the Yarn APT key
      apt_key: url=https://dl.yarnpkg.com/debian/pubkey.gpg
      become: yes

    - name: Add Yarn repository
      apt_repository:
        repo: 'deb https://dl.yarnpkg.com/debian/ stable main'
        state: present
      become: yes

    - name: Install Yarn
      apt: pkg=yarn state=present
      become: yes

    - name: Install gulp
      npm:
        name: gulp
        global: yes
      become: yes

    - name: Refrash machinomy sourse
      git:
        repo: https://github.com/machinomy/machinomy
        dest: "{{ machinomy_path }}"
        update: yes
        accept_hostkey: yes

    - name: Yarn install
      command: yarn install
      args:
        chdir: "{{ machinomy_path }}"

    - name: Yarn build
      command: yarn run build
      args:
        chdir: "{{ machinomy_path }}"

    - name: Refrash ynos sourse
      git:
        repo: git@github.com:machinomy/ynos.git
        dest: "{{ ynos_path }}"
        update: yes
        accept_hostkey: yes

    - name: Yarn install
      command: yarn install
      args:
        chdir: "{{ ynos_path }}"

    - name: Yarn build
      command: yarn run build
      args:
        chdir: "{{ ynos_path }}"

    - name: Yarn build
      command: yarn run build:harness
      args:
        chdir: "{{ ynos_path }}"

    - name: Yarn build
      command: yarn run build:harness
      args:
        chdir: "{{ ynos_path }}"

    - copy:
        remote_src: true
        src: "{{ ynos_path }}/harness/index.html"
        dest: "{{ ynos_path }}/dist/"

    - copy:
        remote_src: true
        src: "{{ ynos_path }}/ynos/frame.html"
        dest: "{{ ynos_path }}/dist/"

    - name: Creates directory
      file:
       path: "/etc/letsencrypt/live/{{site_name}}"
       state: directory
      become: yes

    - name: create self-signed SSL cert
      command: openssl req -new -nodes -x509 -subj "/C=US/ST=Oregon/L=Portland/O=IT/CN=${ansible_fqdn}" -days 3650 -keyout /etc/letsencrypt/live/{{site_name}}/privkey.pem -out /etc/letsencrypt/live/{{site_name}}/fullchain.pem -extensions v3_ca creates=/etc/letsencrypt/live/{{site_name}}/fullchain.pem
      become: yes

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
      become: yes
