---
- hosts: all

  vars:
    vynos_path: '/home/ubuntu/vynos'
    staging_path: '/home/ubuntu/staging'

  environment:
    NODE_ENV: production

  tasks:
    - name: Clone staging
      git:
        repo: git@github.com:machinomy/staging.machinomy.com.git
        dest: "{{ staging_path }}"
        force: yes
        update: yes
        accept_hostkey: yes
      register: gitclonestaging

    - command: yarn install
      args:
        chdir: "{{ staging_path }}"
      when: gitclonestaging.changed

    - command: yarn run build
      args:
        chdir: "{{ staging_path }}"
      when: gitclonestaging.changed

    - name: Clone vynos locally
      local_action: "git repo=git@github.com:machinomy/vynos.git dest=build/vynos update=yes"

    - name: Install deps for vynos locally
      local_action: "command chdir=build/vynos yarn install --pure-lockfile"
      environment:
        NODE_ENV: development

    - name: Build vynos locally
      local_action: "command chdir=build/vynos yarn build"

    - name: Build vynos harness locally
      local_action: "command chdir=build/vynos yarn build:harness"

    - name: Cleanup before copying to the server
      local_action: "file path=build/vynos/dist/dist state=absent"

    - name: Copy vynos to the server
      synchronize:
        src: build/vynos/dist/
        dest: "{{ staging_path }}/public"

    - command: pm2 restart ecosystem.json --env staging
      args:
        chdir: "{{ staging_path }}"