---
- hosts: all
  gather_facts: true

  vars:
    machinomy_path: '~/machinomy'
    vynos_path: '~/vynos'
    staging_path: '~/staging'
    machinomy_contracts_path: '~/machinomy-contracts'

  tasks:
    - name: machinomy-contracts
      git:
        repo: https://github.com/machinomy/machinomy-contracts
        dest: "{{ machinomy_contracts_path }}"
        force: yes
        update: yes
        accept_hostkey: yes

    - command: yarn install
      args:
        chdir: "{{ machinomy_contracts_path }}"

    - name: machinomy
      git:
        repo: https://github.com/machinomy/machinomy
        dest: "{{ machinomy_path }}"
        force: yes
        update: yes
        accept_hostkey: yes

    - command: yarn install
      args:
        chdir: "{{ machinomy_path }}"

    - command: yarn run build
      args:
        chdir: "{{ machinomy_path }}"

    - name: ynos
      git:
        repo: git@github.com:machinomy/vynos.git
        dest: "{{ vynos_path }}"
        force: yes
        update: yes
        accept_hostkey: yes

    - command: yarn install
      args:
        chdir: "{{ vynos_path }}"

    - command: yarn run build
      args:
        chdir: "{{ vynos_path }}"

    - command: yarn run build:harness
      args:
        chdir: "{{ vynos_path }}"

    - name: staging
      git:
        repo: git@github.com:machinomy/staging.machinomy.com.git
        dest: "{{ staging_path }}"
        force: yes
        update: yes
        accept_hostkey: yes

    - command: yarn install
      args:
        chdir: "{{ staging_path }}"

    - command: yarn run build
      args:
        chdir: "{{ staging_path }}"

    - command: webpack
      args:
        chdir: "{{ staging_path }}"

    - copy:
        remote_src: true
        src: "{{ vynos_path }}/dist/{{item}}"
        dest: "{{ staging_path }}/public/"
      with_items:
        - vynos.bundle.js
        - vynos.bundle.js.map
        - frame.bundle.js
        - frame.bundle.js.map
        - worker.bundle.js
        - worker.bundle.js.map

    - command: pm2 restart ecosystem.json --env staging
      args:
        chdir: "{{ staging_path }}"
